Tasks

diff --git a/web_server/0-transfer_file b/web_server/0-transfer_file
--- a/web_server/0-transfer_file
+++ b/web_server/0-transfer_file
@@ -1,14 +1,24 @@
 #!/usr/bin/env bash
-# Transfers a file from Holberton's client to another.
-# Accepts four arguments:
-#    The path to the file to be transferred.
-#    The IP of the server to transfer the file to.
-#    The username that scp connects with.
-#    The path to the SSH private key that scp uses.
+#Bash script that transfers a file from our client to a server:
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# check if there are enough parameters
+if [ $# -lt 4 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# set variables for the parameters
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/
+
+# check the exit code of scp
+if [ $? -eq 0 ]; then
+  echo "File transfer successful"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  echo "File transfer failed"
 fi
